### ISSUE TITLE
Не отправляет данные в Мосэнергосбыт

### ISSUE THREAD

**Issue by kisaev83** [kkuryshev/home_assistant#1]
Добрый день! Подскажите, что не так? Подключил кабинет с помощью вашего компонента к ХА. Появился датчик со всеми моими данными из ЛК, есть служба. Но при вызове службы ничего не происходит - данные не уходят, в логах ничего нет, и события тоже нет.(

**Comment by kkuryshev** [comment]
Добрый день! Обновите компонент (я вчера вечером вносил кое-какие исправления). Кроме того, включите режим дебаг в логах HA (mosenergosbyt: debug). В этом режиме все запросы к порталу логируются и можно увидеть, были ли запрос и возможно была какая-то ошибка. Так же, событие вы только успешное отлавливаете? Там ведь есть еще и событие об ошибке, его смотрели?

**Comment by kisaev83** [comment]
Отлично! Показания через службы отправились. Спасибо. Но события так и не появились в ХА. Или они не должны в нем появиться? Их просто по названию в автоматизации добавлять?

**Comment by kkuryshev** [comment]
Ну для начала я бы посоветовал проверить через UI HA. В одной вкладке вызывать сервис передачи, а в второй заранее подписавшись на событие проверить его получение. <img width="1129" alt="image" src="https://user-images.githubusercontent.com/58146533/82253465-b40b4d00-9959-11ea-945d-3ded23845340.png">. ИМХО справа список отображается только для тех событий, которые используются где-то в автоматизации. Примеры добавления событий в триггеры можно использовать из примеров в readme

**Comment by kisaev83** [comment]
Спасибо за подробный ответ. Всё работает! С меня звезда. Отличный компонент. Я уже не знал как отправлять в мосэнергосбыт данные. Хотел через телефон ботом, но что-то отложил эту затею. А ваш компонент прям выручил.

**Comment by kkuryshev** [comment]
Очень рад, что все получилось ;)
